version: '2.1'

services:
  
  #  rutertider:
  #    restart: always
  #    build: ./flask-rutertider
  #    ports:
  #      - "5000:5000"

  meteogram:
    restart: always
    build: ./meteogram
    ports:
      - "5001:5000"

  wpe:
    restart: always
    build: ./balena-wpe
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      #      - rutertider
      - meteogram

  wifirestart:
    restart: always
    build: ./balena-wifi-restart
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'

  dns:
    build: ./balena-dns/networking
    restart: no
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.dbus: '1'

  telegraf:
    restart: always
    build: ./balena-telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.balena-socket: '1'
    environment:
      - INFLUX_URL=http://10.0.1.202:8086
      - INFLUX_DB=telegraf

