version: '2.1'

services:
  
  rutertider:
    build: ./flask-rutertider
    restart: always
    ports:
      - "5000:5000"

  meteogram:
    build: ./meteogram
    restart: always
    ports:
      - "5001:5000"

  chromekiosk:
    build: ./balena-chromekiosk
    privileged: true
    restart: always
    depends_on:
      - rutertider
      - meteogram

  wifireboot:
    build: ./balena-wifi-reboot
    restart: always
    labels:
      io.balena.features.supervisor-api: '1'

