version: '2.1'

services:
  
  rutertider:
    build: ./flask-rutertider
    restart: always
    ports:
      - "5000:5000"

  meteogram:
    build: ./meteogram
    restart: always
    ports:
      - "5001:5000"

  chromekiosk:
    build: ./balena-chromekiosk
    privileged: true
    restart: always
    depends_on:
      - rutertider
      - meteogram

#  wifireboot:
#    build: ./balena-wifi-reboot
#    restart: always
#    labels:
#      io.balena.features.supervisor-api: '1'

  wifirestart:
    build: ./balena-wifi-restart
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'

  telegraf:
    build: ./balena-telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    environment:
      - INFLUX_URL=http://influxdb.hjemme.nett:8086
      - INFLUX_DB=telegraf

