version: '2.1'

services:
  
  rutertider:
    build: ./flask-rutertider
    ports:
      - "5000:5000"

  meteogram:
    build: ./meteogram
    ports:
      - "5001:5000"

  chromekiosk:
    build: ./balena-chromekiosk
    privileged: true
    labels:
      io.balena.features.dbus: '1'
    depends_on:
      - rutertider
      - meteogram

  wifirestart:
    build: ./balena-wifi-restart
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'

  telegraf:
    build: ./balena-telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.balena-socket: '1'
    environment:
      - INFLUX_URL=http://influxdb.hjemme.nett:8086
      - INFLUX_DB=telegraf

